module.exports = db => {
    const customfunds = [
      {
        "name": "Federal Money Market",
        "ticker": "VMFXX",
        "assetclass": "Money Market",
        "expenseratio": 0.11,
        "price": 1.00,
        "change1": 0.00,
        "change2": 0.00,
        "secyield": 0.01,
        "ytd": 0.01,
        "yr1": 0.01,
        "yr5": 1.04,
        "yr10": 0.55,
        "yrinception":3.95,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VMFXX"
      },
      {
        "name": "Cash Reserves Federal Money Market Admiral Shares",
        "ticker": "VMRXX",
        "assetclass": "Money Market",
        "expenseratio": 0.10,
        "price": 1.00,
        "change1": 0.00,
        "change2": 0.00,
        "secyield": 0.01,
        "ytd": 0.01,
        "yr1": 0.01,
        "yr5": 1.20,
        "yr10": 0.68,
        "yrinception":2.94,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VMRXX"
      },
      {
        "name": "Treasury Money Market",
        "ticker": "VUSXX",
        "assetclass": "Money Market",
        "expenseratio": 0.09,
        "price": 1.00,
        "change1": 0.00,
        "change2": 0.00,
        "secyield": 0.01,
        "ytd": 0.01,
        "yr1": 0.02,
        "yr5": 1.04,
        "yr10": 0.55,
        "yrinception":2.31,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VUSXX"
      },
      {
        "name": "California Municipal Money Market",
        "ticker": "VCTXX",
        "assetclass": "Money Market",
        "expenseratio": 0.16,
        "price": 1.00,
        "change1": 0.00,
        "change2": 0.00,
        "secyield": 0.01,
        "ytd": 0.01,
        "yr1": 0.02,
        "yr5": 1.04,
        "yr10": 0.55,
        "yrinception":2.31
      },
      {
        "name": "California Municipal Money Market",
        "ticker": "VCTXX",
        "assetclass": "Money Market",
        "expenseratio": 0.11,
        "price": 1.00,
        "change1": 0.00,
        "change2": 0.00,
        "secyield": 0.01,
        "ytd": 0.01,
        "yr1": 0.01,
        "yr5": 0.72,
        "yr10": 0.39,
        "yrinception":2.09,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VCTXX"
      },
      {
        "name": "Municipal Money Market",
        "ticker": "VMSXX",
        "assetclass": "Money Market",
        "expenseratio": 0.15,
        "price": 1.00,
        "change1": 0.00,
        "change2": 0.00,
        "secyield": 0.01,
        "ytd": 0.01,
        "yr1": 0.01,
        "yr5": 0.80,
        "yr10": 0.44,
        "yrinception":2.76,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VMSXX"
      },
      {
        "name": "New York Municipal Money Market",
        "ticker": "VYFXX",
        "assetclass": "Money Market",
        "expenseratio": 0.16,
        "price": 1.00,
        "change1": 0.00,
        "change2": 0.00,
        "secyield": 0.01,
        "ytd": 0.01,
        "yr1": 0.01,
        "yr5": 0.77,
        "yr10": 0.42,
        "yrinception": 1.36,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VYFXX"
      },
      {
        "name": "Target Retirement 2015",
        "ticker": "VTXVX",
        "assetclass": "Balanced",
        "expenseratio": 0.12,
        "price": 16.58,
        "change1": 0.06,
        "change2": 0.36,
        "secyield": 1.74,
        "ytd": 5.40,
        "yr1": 6.72,
        "yr5": 7.71,
        "yr10": 7.39,
        "yrinception":6.42,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VTXVX"
      },
      {
        "name": "Target Retirement 2020",
        "ticker": "VTWNX",
        "assetclass": "Balanced",
        "expenseratio": 0.13,
        "price": 36.89,
        "change1": 0.17,
        "change2": 0.46,
        "secyield": 1.67,
        "ytd": 7.58,
        "yr1": 9.25,
        "yr5": 9.19,
        "yr10": 8.57,
        "yrinception":6.86,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VTWNX"
      },
      {
        "name": "Target Retirement 2025",
        "ticker": "VTTVX",
        "assetclass": "Balanced",
        "expenseratio": 0.13,
        "price": 23.48,
        "change1": 0.12,
        "change2": 0.51,
        "secyield": 1.54,
        "ytd": 9.01,
        "yr1": 10.86,
        "yr5": 10.21,
        "yr10": 9.40,
        "yrinception":7.39,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VTTVX"
      },
      {
        "name": "Target Retirement 2030",
        "ticker": "VTHRX",
        "assetclass": "Balanced",
        "expenseratio": 0.14,
        "price": 44.79,
        "change1": 0.27,
        "change2": 0.61,
        "secyield": 1.54,
        "ytd": 10.46,
        "yr1": 12.49,
        "yr5": 11.03,
        "yr10": 10.11,
        "yrinception":7.52,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VTHRX"
      },
      {
        "name": "Target Retirement 2035",
        "ticker": "VTTHX",
        "assetclass": "Balanced",
        "expenseratio": 0.14,
        "price": 28.22,
        "change1": 0.19,
        "change2": 0.68,
        "secyield": 1.57,
        "ytd": 11.90,
        "yr1": 14.11,
        "yr5": 11.81,
        "yr10": 10.80,
        "yrinception":8.18,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VTTHX"
      },
      {
        "name": "Target Retirement 2040",
        "ticker": "VFORX",
        "assetclass": "Balanced",
        "expenseratio": 0.14,
        "price": 50.17,
        "change1": 0.37,
        "change2": 0.74,
        "secyield": 1.59,
        "ytd": 13.33,
        "yr1": 15.76,
        "yr5": 12.60,
        "yr10": 11.34,
        "yrinception":8.15,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VFORX"
      },
      {
        "name": "Target Retirement 2045",
        "ticker": "VTIVX",
        "assetclass": "Balanced",
        "expenseratio": 0.15,
        "price": 32.35,
        "change1": 0.25,
        "change2": 0.78,
        "secyield": 1.61,
        "ytd": 14.76,
        "yr1": 17.39,
        "yr5": 13.19,
        "yr10": 11.65,
        "yrinception":8.81,
        "website": "https://investor.vanguard.com/mutual-funds/profile/VTIVX"
      }
    ]
  
    customfunds.forEach(customfund => db.customfunds.insert(customfund))
  }
  